# Generated by Django 2.2.6 on 2019-10-26 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share_member', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharemember',
            name='middle_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
