# Generated by Django 2.2.6 on 2019-10-26 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share_member', '0002_sharemember_middle_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharemember',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
