# Generated by Django 2.2.6 on 2019-10-26 16:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('share_member', '0003_sharemember_updatedat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharemember',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='sharemember',
            name='createdBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member_created_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
