# Generated by Django 2.2.6 on 2019-10-26 16:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('share_member', '0004_auto_20191026_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharemember',
            name='createdBy',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member_created_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
