# Generated by Django 2.2.6 on 2019-10-31 15:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import loan.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('share_member', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanAccount',
            fields=[
                ('id', models.IntegerField(default=loan.models.ids, editable=False, unique=True)),
                ('loan_number', models.CharField(editable=False, max_length=50, primary_key=True, serialize=False)),
                ('amount_received', models.DecimalField(decimal_places=10, max_digits=19)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('createdBy', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'loan_account',
            },
        ),
        migrations.CreateModel(
            name='LoanPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid', models.DecimalField(decimal_places=10, max_digits=19)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('createdBy', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('loan_account', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='loan.LoanAccount')),
            ],
            options={
                'db_table': 'loan_payment',
            },
        ),
        migrations.CreateModel(
            name='LoanType',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('interest_rate', models.IntegerField()),
                ('slug', models.SlugField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('createdBy', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'loan_type',
            },
        ),
        migrations.CreateModel(
            name='LoanPaymentHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('principle', models.DecimalField(decimal_places=10, max_digits=19)),
                ('interest', models.DecimalField(decimal_places=10, max_digits=19)),
                ('paid', models.DecimalField(decimal_places=10, max_digits=19)),
                ('remaining', models.DecimalField(decimal_places=10, max_digits=19)),
                ('loan_payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loan.LoanPayment')),
            ],
            options={
                'db_table': 'loan_detail',
            },
        ),
        migrations.AddField(
            model_name='loanaccount',
            name='loan_type',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='loan.LoanType'),
        ),
        migrations.AddField(
            model_name='loanaccount',
            name='share_member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='share_member.ShareMember'),
        ),
    ]
