# Generated by Django 2.2.6 on 2019-10-31 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanpayment',
            name='loan_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loan.LoanAccount'),
        ),
    ]
