# Generated by Django 2.2.6 on 2019-10-31 16:46

from django.db import migrations, models
import loan.models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0002_auto_20191031_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanpayment',
            name='id',
            field=models.IntegerField(default=loan.models.ids, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='loanpaymenthistory',
            name='id',
            field=models.IntegerField(default=loan.models.ids, editable=False, primary_key=True, serialize=False),
        ),
    ]
