# Generated by Django 2.2.6 on 2019-11-03 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0002_auto_20191103_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanaccount',
            name='amount_received',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='loanpayment',
            name='paid',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='loanpaymenthistory',
            name='interest',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='loanpaymenthistory',
            name='paid',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='loanpaymenthistory',
            name='principle',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='loanpaymenthistory',
            name='remaining',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
