# Generated by Django 2.2.6 on 2019-10-31 17:04

from django.db import migrations, models
import loan.models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0003_auto_20191031_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanpayment',
            name='id',
            field=models.IntegerField(default=loan.models.loan_payment_ids, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='loanpaymenthistory',
            name='id',
            field=models.IntegerField(default=loan.models.loan_payment_history_ids, editable=False, primary_key=True, serialize=False),
        ),
    ]
