# Generated by Django 2.2.6 on 2019-11-03 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0003_auto_20191103_2102'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='loanpaymenthistory',
            table='loan_payment_history',
        ),
    ]
