# Generated by Django 2.2.6 on 2019-10-31 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0004_auto_20191031_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanaccount',
            name='status',
            field=models.CharField(choices=[('OPEN', 'OPEN'), ('CLOSED', 'CLOSED')], default='OPEN', max_length=50, verbose_name='Status Type'),
        ),
    ]
