# Generated by Django 2.2.6 on 2019-11-03 11:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import saving_account.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('share_member', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavingType',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('account_type', models.CharField(choices=[('-', '-'), ('DAILY', 'DAILY'), ('MONTHLY', 'MONTHLY')], default='-', max_length=50, verbose_name='Account Type')),
                ('slug', models.SlugField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('interest_rate', models.IntegerField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('createdBy', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'saving_type',
            },
        ),
        migrations.CreateModel(
            name='SavingAccount',
            fields=[
                ('id', models.IntegerField(default=saving_account.models.ids, editable=False, unique=True)),
                ('account_number', models.CharField(editable=False, max_length=50, primary_key=True, serialize=False)),
                ('time_in_yr', models.IntegerField(null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('createdBy', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('saving_type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='saving_account.SavingType')),
                ('share_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='share_member.ShareMember')),
            ],
            options={
                'db_table': 'saving_account',
            },
        ),
        migrations.CreateModel(
            name='Saving',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('particular', models.CharField(max_length=200, null=True)),
                ('amount', models.IntegerField()),
                ('amount_type', models.CharField(choices=[('Dr', 'DEBIT'), ('Cr', 'CREDIT')], max_length=50, verbose_name='Amount Type')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('createdBy', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('saving_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saving_account.SavingAccount')),
            ],
            options={
                'db_table': 'saving',
            },
        ),
    ]
